version: '3.7'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:3306
  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
      - type: bind
        source: ./docker_db
        target: /docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_DATABASE: bd_biblioteca
      MYSQL_USER: biblioteca
      MYSQL_ROOT_PASSWORD: biblioteca
      MYSQL_PASSWORD: biblioteca

volumes:
  db:
    