version: '3'
services:
  app:
    build: biblioteca
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: mysql:5.7
    environment:
        MYSQL_DATABASE: biblioteca
        MYSQL_USER: sofi
        MYSQL_PASSWORD: sofi
        MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
