version: '3.3'
services:
  db:
    image: mysql:5.7
    # restart: always
    volumes:
      - db:/var/lib/mysql
      - type: bind
        source: ./docker_db/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: 'jose-emi'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
  
  app_biblioteca:
    build: ./docker_app
    depends_on:
        - db
    ports:
        - "8080:8080"
    environment:
      WAIT_HOSTS: db:3306
     
# Names our volume
volumes:
  db: 